# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Poplar' do
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

end
